name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: |
        cd ./src
        dotnet restore

    # Build the solution
    - name: Build solution
      run: |
        cd ./src
        dotnet build --configuration Release

    # Run tests
    - name: Run tests
      run: |
        cd ./src
        dotnet test --configuration Release 
