name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    # Change directory to the folder containing the solution file
    - name: Change directory to src
      run: cd src

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Set environment variable for architecture
    - name: Set architecture
      run: echo "DOTNET_HOST_X64=1" >> $GITHUB_ENV

    # Build the solution in Release configuration
    - name: Build solution
      run: dotnet build --configuration Release

    # Run tests in Release configuration
    - name: Run tests
      run: dotnet test --configuration Release
