name: .NET Core CI with ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Latest version

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3  # Latest version
      with:
        dotnet-version: '7.0.x'  # Latest .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
